-- 001_provider_security_market_data
CREATE SCHEMA IF NOT EXISTS SP;

CREATE TABLE IF NOT EXISTS SP.schema_migration_note (
    migration_name VARCHAR(128) NOT NULL PRIMARY KEY,
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    checksum VARCHAR(128)
);

CREATE TABLE IF NOT EXISTS SP.data_provider (
    provider_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_code VARCHAR(64) NOT NULL,
    provider_name VARCHAR(255) NOT NULL,
    provider_type VARCHAR(32) NOT NULL,
    base_url VARCHAR(512),
    auth_type VARCHAR(32),
    status VARCHAR(32) DEFAULT 'active' NOT NULL,
    rate_limit_per_minute BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_active BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_data_provider_code
    ON SP.data_provider (provider_code);

CREATE TABLE IF NOT EXISTS SP.data_license (
    data_license_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    license_name VARCHAR(255) NOT NULL,
    can_store BOOLEAN DEFAULT FALSE NOT NULL,
    can_transform BOOLEAN DEFAULT FALSE NOT NULL,
    can_display_realtime BOOLEAN DEFAULT FALSE NOT NULL,
    can_redistribute BOOLEAN DEFAULT FALSE NOT NULL,
    effective_from TIMESTAMP,
    effective_to TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SP.security_master (
    security_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(64) NOT NULL,
    security_name VARCHAR(255) NOT NULL,
    market_code VARCHAR(32) NOT NULL,
    country_code VARCHAR(3) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    asset_type VARCHAR(32) NOT NULL,
    exchange_code VARCHAR(32),
    business_group_id BIGINT,
    listed_at TIMESTAMP,
    delisted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    is_active BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_security_market_symbol
    ON SP.security_master (market_code, symbol);

CREATE TABLE IF NOT EXISTS SP.provider_symbol_map (
    provider_symbol_map_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    security_id BIGINT NOT NULL,
    provider_symbol VARCHAR(128) NOT NULL,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SP.price_bar (
    price_bar_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    bar_interval VARCHAR(16) NOT NULL,
    market_date DATE NOT NULL,
    bar_ts TIMESTAMP NOT NULL,
    open_price NUMERIC(24, 8),
    high_price NUMERIC(24, 8),
    low_price NUMERIC(24, 8),
    close_price NUMERIC(24, 8),
    volume NUMERIC(24, 4),
    turnover_krw NUMERIC(24, 4),
    loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    available_to_model_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_price_bar_key
    ON SP.price_bar (security_id, provider_id, bar_interval, bar_ts);

CREATE TABLE IF NOT EXISTS SP.raw_data_manifest (
    raw_data_manifest_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    dataset_name VARCHAR(128) NOT NULL,
    source_uri VARCHAR(1024),
    storage_uri VARCHAR(1024) NOT NULL,
    content_sha256 VARCHAR(128),
    loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    quality_status VARCHAR(32) DEFAULT 'pending' NOT NULL
);

CREATE TABLE IF NOT EXISTS SP.data_quality_run (
    data_quality_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_name VARCHAR(128) NOT NULL,
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    quality_status VARCHAR(32) NOT NULL,
    issue_count BIGINT DEFAULT 0 NOT NULL,
    detail LONG VARCHAR
);
