-- 002_account_fifo
CREATE TABLE IF NOT EXISTS SP.account (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_code VARCHAR(64) NOT NULL,
    account_name VARCHAR(255) NOT NULL,
    account_mode VARCHAR(32) NOT NULL,
    base_currency VARCHAR(3) DEFAULT 'KRW' NOT NULL,
    broker_code VARCHAR(64),
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_account_code
    ON SP.account (account_code);

CREATE TABLE IF NOT EXISTS SP.transaction_ledger (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    security_id BIGINT NOT NULL,
    transaction_type VARCHAR(32) NOT NULL,
    side VARCHAR(8),
    quantity NUMERIC(24, 8) NOT NULL,
    price NUMERIC(24, 8) NOT NULL,
    trade_currency VARCHAR(3) NOT NULL,
    trade_amount NUMERIC(24, 8) NOT NULL,
    trade_amount_krw NUMERIC(24, 4),
    fee_krw NUMERIC(24, 4) DEFAULT 0 NOT NULL,
    tax_krw NUMERIC(24, 4) DEFAULT 0 NOT NULL,
    trade_date DATE NOT NULL,
    settlement_date DATE,
    source_event_type VARCHAR(32) NOT NULL,
    source_event_id BIGINT,
    booked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    correction_of_id BIGINT,
    is_reversal BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_transaction_account_security
    ON SP.transaction_ledger (account_id, security_id, trade_date);

CREATE TABLE IF NOT EXISTS SP.cash_ledger (
    cash_ledger_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    amount NUMERIC(24, 8) NOT NULL,
    amount_krw NUMERIC(24, 4),
    cash_event_type VARCHAR(32) NOT NULL,
    source_transaction_id BIGINT,
    booked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS SP.position_lot (
    position_lot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    security_id BIGINT NOT NULL,
    buy_transaction_id BIGINT NOT NULL,
    lot_version BIGINT DEFAULT 1 NOT NULL,
    acquired_date DATE NOT NULL,
    original_quantity NUMERIC(24, 8) NOT NULL,
    remaining_quantity NUMERIC(24, 8) NOT NULL,
    unit_cost NUMERIC(24, 8) NOT NULL,
    unit_cost_krw NUMERIC(24, 4),
    status VARCHAR(32) DEFAULT 'open' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_position_lot_fifo
    ON SP.position_lot (account_id, security_id, acquired_date, position_lot_id);

CREATE TABLE IF NOT EXISTS SP.fifo_lot_match (
    fifo_lot_match_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sell_transaction_id BIGINT NOT NULL,
    position_lot_id BIGINT NOT NULL,
    matched_quantity NUMERIC(24, 8) NOT NULL,
    buy_unit_cost_krw NUMERIC(24, 4),
    sell_unit_price_krw NUMERIC(24, 4),
    allocated_fee_krw NUMERIC(24, 4) DEFAULT 0 NOT NULL,
    allocated_tax_krw NUMERIC(24, 4) DEFAULT 0 NOT NULL,
    matched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS SP.realized_pnl (
    realized_pnl_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fifo_lot_match_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    security_id BIGINT NOT NULL,
    realized_date DATE NOT NULL,
    realized_pnl_krw NUMERIC(24, 4) NOT NULL,
    realized_return_pct NUMERIC(12, 6),
    holding_days BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
