-- 003_risk_order_backup
CREATE TABLE IF NOT EXISTS SP.risk_limit (
    risk_limit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    limit_code VARCHAR(64) NOT NULL,
    scope_type VARCHAR(32) NOT NULL,
    warning_value NUMERIC(24, 8),
    block_value NUMERIC(24, 8),
    stop_value NUMERIC(24, 8),
    unit VARCHAR(32) NOT NULL,
    valid_from TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    valid_to TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_risk_limit_active
    ON SP.risk_limit (limit_code, scope_type, valid_from);

CREATE TABLE IF NOT EXISTS SP.slippage_rule (
    slippage_rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_code VARCHAR(32) NOT NULL,
    order_type VARCHAR(32) NOT NULL,
    base_slippage_bps NUMERIC(12, 4) NOT NULL,
    low_liquidity_multiplier NUMERIC(12, 4) DEFAULT 3.0 NOT NULL,
    low_liquidity_adv20_floor_krw NUMERIC(24, 4) DEFAULT 1000000000 NOT NULL,
    valid_from TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    valid_to TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE IF NOT EXISTS SP.order_request (
    order_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(128) NOT NULL,
    account_id BIGINT NOT NULL,
    security_id BIGINT NOT NULL,
    market_code VARCHAR(32) NOT NULL,
    side VARCHAR(8) NOT NULL,
    order_type VARCHAR(32) NOT NULL,
    price NUMERIC(24, 8),
    quantity NUMERIC(24, 8) NOT NULL,
    order_amount_krw NUMERIC(24, 4) NOT NULL,
    account_mode VARCHAR(32) NOT NULL,
    status VARCHAR(32) DEFAULT 'draft' NOT NULL,
    broker_order_id VARCHAR(128),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_order_idempotency
    ON SP.order_request (idempotency_key);

CREATE TABLE IF NOT EXISTS SP.risk_check_result (
    risk_check_result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_request_id BIGINT,
    result_status VARCHAR(32) NOT NULL,
    checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rule_version VARCHAR(64) NOT NULL,
    detail LONG VARCHAR
);

CREATE TABLE IF NOT EXISTS SP.execution (
    execution_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_request_id BIGINT NOT NULL,
    broker_execution_id VARCHAR(128),
    executed_at TIMESTAMP NOT NULL,
    executed_price NUMERIC(24, 8) NOT NULL,
    executed_quantity NUMERIC(24, 8) NOT NULL,
    fee_krw NUMERIC(24, 4) DEFAULT 0 NOT NULL,
    tax_krw NUMERIC(24, 4) DEFAULT 0 NOT NULL,
    raw_response LONG VARCHAR
);

CREATE TABLE IF NOT EXISTS SP.db_backup_policy (
    backup_policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_code VARCHAR(64) NOT NULL,
    schedule_cron VARCHAR(64) NOT NULL,
    timezone VARCHAR(64) DEFAULT 'Asia/Seoul' NOT NULL,
    base_path VARCHAR(1024) NOT NULL,
    retention_days BIGINT,
    encryption_type VARCHAR(32) DEFAULT 'none' NOT NULL,
    is_active BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_db_backup_policy_code
    ON SP.db_backup_policy (policy_code);

CREATE TABLE IF NOT EXISTS SP.db_backup_run (
    backup_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backup_policy_id BIGINT NOT NULL,
    scheduled_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    status VARCHAR(32) NOT NULL,
    backup_path VARCHAR(1024),
    total_bytes BIGINT,
    checksum_status VARCHAR(32),
    error_message LONG VARCHAR
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_backup_policy_schedule
    ON SP.db_backup_run (backup_policy_id, scheduled_at);
