-- 005_simulation_ml_group_index
CREATE TABLE IF NOT EXISTS SP.virtual_account_profile (
    virtual_account_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_code VARCHAR(64) NOT NULL,
    profile_name VARCHAR(255) NOT NULL,
    initial_cash_krw NUMERIC(24, 4) DEFAULT 100000000 NOT NULL,
    initial_cash_usd NUMERIC(24, 4) DEFAULT 0 NOT NULL,
    fill_delay_seconds BIGINT DEFAULT 1 NOT NULL,
    partial_fill_volume_ratio NUMERIC(12, 6) DEFAULT 0.05 NOT NULL,
    replay_daily_years BIGINT DEFAULT 3 NOT NULL,
    replay_intraday_months BIGINT DEFAULT 6 NOT NULL,
    is_active BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_virtual_account_profile_code
    ON SP.virtual_account_profile (profile_code);

CREATE TABLE IF NOT EXISTS SP.simulation_session (
    simulation_session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    virtual_account_profile_id BIGINT NOT NULL,
    account_id BIGINT,
    session_name VARCHAR(255) NOT NULL,
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ended_at TIMESTAMP,
    status VARCHAR(32) DEFAULT 'running' NOT NULL,
    replay_from DATE,
    replay_to DATE,
    result_summary LONG VARCHAR
);

CREATE TABLE IF NOT EXISTS SP.business_group (
    business_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_code VARCHAR(64) NOT NULL,
    group_name VARCHAR(255) NOT NULL,
    taxonomy_source VARCHAR(64) NOT NULL,
    manual_override_flag BOOLEAN DEFAULT FALSE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_business_group_code
    ON SP.business_group (group_code);

CREATE TABLE IF NOT EXISTS SP.business_group_member (
    business_group_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_group_id BIGINT NOT NULL,
    security_id BIGINT NOT NULL,
    membership_basis VARCHAR(32) DEFAULT 'current' NOT NULL,
    weight_method VARCHAR(32) DEFAULT 'market_cap_weight' NOT NULL,
    valid_from TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    valid_to TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SP.ml_analysis_job (
    ml_analysis_job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id BIGINT NOT NULL,
    prediction_horizon VARCHAR(16) NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    model_version VARCHAR(64) NOT NULL,
    feature_set_version VARCHAR(64) NOT NULL,
    status VARCHAR(32) DEFAULT 'queued' NOT NULL,
    requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    failure_reason LONG VARCHAR
);

CREATE TABLE IF NOT EXISTS SP.ml_prediction_result (
    ml_prediction_result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ml_analysis_job_id BIGINT NOT NULL,
    security_id BIGINT NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    horizon VARCHAR(16) NOT NULL,
    predicted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    lower_value NUMERIC(24, 8),
    median_value NUMERIC(24, 8),
    upper_value NUMERIC(24, 8),
    confidence_score NUMERIC(12, 6),
    quality_status VARCHAR(32) DEFAULT 'ok' NOT NULL
);

CREATE TABLE IF NOT EXISTS SP.risk_index_formula_version (
    formula_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    formula_code VARCHAR(64) NOT NULL,
    formula_type VARCHAR(32) NOT NULL,
    input_spec LONG VARCHAR,
    weight_spec LONG VARCHAR,
    normalization_spec LONG VARCHAR,
    valid_from TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    valid_to TIMESTAMP,
    status VARCHAR(32) DEFAULT 'active' NOT NULL
);

CREATE TABLE IF NOT EXISTS SP.security_volatility_index (
    security_volatility_index_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id BIGINT NOT NULL,
    index_ts TIMESTAMP NOT NULL,
    formula_version_id BIGINT NOT NULL,
    raw_volatility NUMERIC(24, 8),
    volatility_index NUMERIC(12, 6),
    quality_status VARCHAR(32) DEFAULT 'ok' NOT NULL
);

CREATE TABLE IF NOT EXISTS SP.security_risk_index (
    security_risk_index_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id BIGINT NOT NULL,
    index_ts TIMESTAMP NOT NULL,
    formula_version_id BIGINT NOT NULL,
    risk_score NUMERIC(12, 6),
    risk_level VARCHAR(32),
    component_scores LONG VARCHAR,
    quality_status VARCHAR(32) DEFAULT 'ok' NOT NULL
);

INSERT INTO SP.virtual_account_profile (
    profile_code,
    profile_name,
    initial_cash_krw,
    initial_cash_usd,
    fill_delay_seconds,
    partial_fill_volume_ratio,
    replay_daily_years,
    replay_intraday_months
)
SELECT
    'mvp_default',
    'MVP Default Virtual Account',
    100000000,
    0,
    1,
    0.05,
    3,
    6
WHERE NOT EXISTS (
    SELECT 1 FROM SP.virtual_account_profile
    WHERE profile_code = 'mvp_default'
);

INSERT INTO SP.risk_index_formula_version (
    formula_code,
    formula_type,
    input_spec,
    weight_spec,
    normalization_spec
)
SELECT
    'VOL_EWMA_V1',
    'volatility',
    'lambda=0.94,trading_days=252,lookback=252',
    NULL,
    'percentile_0_100'
WHERE NOT EXISTS (
    SELECT 1 FROM SP.risk_index_formula_version
    WHERE formula_code = 'VOL_EWMA_V1'
);

INSERT INTO SP.risk_index_formula_version (
    formula_code,
    formula_type,
    input_spec,
    weight_spec,
    normalization_spec
)
SELECT
    'RISK_SCORE_V1',
    'risk',
    'volatility,drawdown,liquidity,event,group,ml',
    '25,20,15,20,10,10',
    'clamp_0_100'
WHERE NOT EXISTS (
    SELECT 1 FROM SP.risk_index_formula_version
    WHERE formula_code = 'RISK_SCORE_V1'
);
