-- 006_order_controls_audit
CREATE TABLE IF NOT EXISTS SP.order_state_event (
    order_state_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_request_id BIGINT NOT NULL,
    from_status VARCHAR(32) NOT NULL,
    to_status VARCHAR(32) NOT NULL,
    occurred_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    filled_quantity_delta NUMERIC(24, 8) DEFAULT 0 NOT NULL,
    reason VARCHAR(512)
);

CREATE INDEX IF NOT EXISTS ix_order_state_event_order
    ON SP.order_state_event (order_request_id, occurred_at);

CREATE TABLE IF NOT EXISTS SP.order_idempotency_key (
    order_idempotency_key_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(128) NOT NULL,
    order_request_id BIGINT NOT NULL,
    reserved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_order_idempotency_key
    ON SP.order_idempotency_key (idempotency_key);

CREATE TABLE IF NOT EXISTS SP.kill_switch_state (
    kill_switch_state_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type VARCHAR(32) NOT NULL,
    scope_value VARCHAR(128) NOT NULL,
    is_blocking BOOLEAN DEFAULT TRUE NOT NULL,
    reason VARCHAR(512),
    activated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deactivated_at TIMESTAMP,
    created_by VARCHAR(128)
);

CREATE INDEX IF NOT EXISTS ix_kill_switch_active
    ON SP.kill_switch_state (scope_type, scope_value, is_blocking, activated_at);

CREATE TABLE IF NOT EXISTS SP.event_risk_signal (
    event_risk_signal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_event_type VARCHAR(32) NOT NULL,
    source_event_id VARCHAR(128) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    security_id BIGINT,
    business_group_id BIGINT,
    observed_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP,
    detail LONG VARCHAR
);

CREATE INDEX IF NOT EXISTS ix_event_risk_active_security
    ON SP.event_risk_signal (security_id, severity, observed_at);

CREATE INDEX IF NOT EXISTS ix_event_risk_active_group
    ON SP.event_risk_signal (business_group_id, severity, observed_at);

CREATE TABLE IF NOT EXISTS SP.reconciliation_run (
    reconciliation_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    broker_code VARCHAR(64) NOT NULL,
    reconciled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status VARCHAR(32) NOT NULL,
    issue_count BIGINT DEFAULT 0 NOT NULL,
    detail LONG VARCHAR
);

CREATE TABLE IF NOT EXISTS SP.audit_log (
    audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_type VARCHAR(32) NOT NULL,
    actor_id VARCHAR(128),
    action_code VARCHAR(128) NOT NULL,
    target_type VARCHAR(64) NOT NULL,
    target_id VARCHAR(128),
    occurred_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    detail LONG VARCHAR
);
