-- 007_ml_watchlist_performance
CREATE TABLE IF NOT EXISTS SP.user_watchlist (
    user_watchlist_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL,
    security_id BIGINT NOT NULL,
    note VARCHAR(512),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deactivated_at TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_watchlist_active
    ON SP.user_watchlist (user_id, security_id, is_active);

CREATE TABLE IF NOT EXISTS SP.ml_prediction_actual (
    ml_prediction_actual_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ml_prediction_result_id BIGINT NOT NULL,
    actual_value NUMERIC(24, 8) NOT NULL,
    observed_at TIMESTAMP NOT NULL,
    absolute_error NUMERIC(24, 8),
    pct_error NUMERIC(18, 8),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_ml_prediction_actual_result
    ON SP.ml_prediction_actual (ml_prediction_result_id, observed_at);

CREATE TABLE IF NOT EXISTS SP.ml_model_performance_summary (
    ml_model_performance_summary_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id BIGINT NOT NULL,
    model_version VARCHAR(64) NOT NULL,
    horizon VARCHAR(16) NOT NULL,
    sample_count BIGINT DEFAULT 0 NOT NULL,
    mean_absolute_error NUMERIC(24, 8),
    mean_absolute_pct_error NUMERIC(18, 8),
    calculated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_ml_model_performance_security
    ON SP.ml_model_performance_summary (security_id, model_version, horizon, calculated_at);

CREATE TABLE IF NOT EXISTS SP.index_chart_snapshot (
    index_chart_snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id BIGINT NOT NULL,
    chart_type VARCHAR(32) NOT NULL,
    start_at TIMESTAMP,
    end_at TIMESTAMP,
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    point_count BIGINT DEFAULT 0 NOT NULL,
    payload LONG VARCHAR
);
