-- 008_backtest_restore_operations
CREATE TABLE IF NOT EXISTS SP.backtest_run (
    backtest_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_code VARCHAR(128) NOT NULL,
    strategy_id VARCHAR(128) NOT NULL,
    market_scope VARCHAR(16) DEFAULT 'BOTH' NOT NULL,
    from_date DATE NOT NULL,
    to_date DATE NOT NULL,
    initial_cash_krw NUMERIC(24, 4) NOT NULL,
    status VARCHAR(32) DEFAULT 'queued' NOT NULL,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    result_summary LONG VARCHAR
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_backtest_run_code
    ON SP.backtest_run (run_code);

CREATE TABLE IF NOT EXISTS SP.backtest_order_event (
    backtest_order_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backtest_run_id BIGINT NOT NULL,
    security_id BIGINT,
    side VARCHAR(8) NOT NULL,
    order_type VARCHAR(32) NOT NULL,
    order_price NUMERIC(24, 8) NOT NULL,
    quantity NUMERIC(24, 8) NOT NULL,
    decision_at TIMESTAMP NOT NULL,
    accepted BOOLEAN DEFAULT FALSE NOT NULL,
    reason VARCHAR(128) NOT NULL,
    realized_pnl_krw NUMERIC(24, 4) DEFAULT 0 NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_backtest_order_event_run
    ON SP.backtest_order_event (backtest_run_id, decision_at);

CREATE TABLE IF NOT EXISTS SP.backtest_metric (
    backtest_metric_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backtest_run_id BIGINT NOT NULL,
    metric_code VARCHAR(128) NOT NULL,
    metric_value NUMERIC(24, 8) NOT NULL,
    calculated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS SP.scenario_result (
    scenario_result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_code VARCHAR(128) NOT NULL,
    scenario_name VARCHAR(255) NOT NULL,
    shocked_price NUMERIC(24, 8),
    shocked_fx_rate NUMERIC(24, 8),
    shocked_turnover_krw NUMERIC(24, 4),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    detail LONG VARCHAR
);

CREATE TABLE IF NOT EXISTS SP.restore_check_run (
    restore_check_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backup_run_id BIGINT,
    manifest_path VARCHAR(1024) NOT NULL,
    checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status VARCHAR(32) NOT NULL,
    issue_count BIGINT DEFAULT 0 NOT NULL,
    issues LONG VARCHAR
);
