-- 009_verification_alert_evidence
CREATE TABLE IF NOT EXISTS SP.verification_gate_assessment (
    verification_gate_assessment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gate_id VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    passed_count BIGINT DEFAULT 0 NOT NULL,
    total_count BIGINT DEFAULT 0 NOT NULL,
    assessed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    detail LONG VARCHAR
);

CREATE INDEX IF NOT EXISTS ix_verification_gate_assessment_gate
    ON SP.verification_gate_assessment (gate_id, assessed_at);

CREATE TABLE IF NOT EXISTS SP.verification_gate_evidence (
    verification_gate_evidence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    verification_gate_assessment_id BIGINT,
    gate_id VARCHAR(32) NOT NULL,
    requirement_id VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    evidence_uri VARCHAR(1024) NOT NULL,
    checked_at TIMESTAMP NOT NULL,
    detail LONG VARCHAR
);

CREATE INDEX IF NOT EXISTS ix_verification_gate_evidence_gate
    ON SP.verification_gate_evidence (gate_id, requirement_id, checked_at);

CREATE TABLE IF NOT EXISTS SP.alert_delivery_run (
    alert_delivery_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_code VARCHAR(64) NOT NULL,
    alert_id VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    delivered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    error_message LONG VARCHAR
);

CREATE INDEX IF NOT EXISTS ix_alert_delivery_run_alert
    ON SP.alert_delivery_run (alert_id, delivered_at);
