-- 010_headline_event_pipeline
CREATE TABLE IF NOT EXISTS SP.headline_event (
    headline_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_code VARCHAR(64) NOT NULL,
    provider_raw_ref VARCHAR(1024),
    headline VARCHAR(2048) NOT NULL,
    published_at TIMESTAMP NOT NULL,
    source_url VARCHAR(2048) NOT NULL,
    security_ids LONG VARCHAR,
    group_ids LONG VARCHAR,
    event_tags LONG VARCHAR,
    metadata LONG VARCHAR,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_headline_event_provider_ref
    ON SP.headline_event (provider_code, provider_raw_ref);

CREATE INDEX IF NOT EXISTS ix_headline_event_published
    ON SP.headline_event (published_at);

CREATE TABLE IF NOT EXISTS SP.headline_dedup_cluster (
    headline_dedup_cluster_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cluster_code VARCHAR(64) NOT NULL,
    representative_provider_code VARCHAR(64) NOT NULL,
    representative_headline VARCHAR(2048) NOT NULL,
    representative_published_at TIMESTAMP NOT NULL,
    provider_count BIGINT DEFAULT 0 NOT NULL,
    headline_count BIGINT DEFAULT 0 NOT NULL,
    source_urls LONG VARCHAR,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_headline_dedup_cluster_code
    ON SP.headline_dedup_cluster (cluster_code);

CREATE TABLE IF NOT EXISTS SP.headline_risk_signal (
    headline_risk_signal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cluster_code VARCHAR(64) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    observed_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP,
    security_ids LONG VARCHAR,
    group_ids LONG VARCHAR,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_headline_risk_signal_active
    ON SP.headline_risk_signal (event_type, severity, observed_at, expires_at);
